AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Programmatic EC2 job runner. Launches a user-selectable instance type (default r8g.16xlarge, Graviton 4) with Nitro Enclaves enabled, using the latest AL2023 Arm64 AMI (automatically resolved via SSM). Copies user chosen files and script to the instance and runs the user script as ec2-user in a tmux session.

# ------------------------------------------------------------
# Parameters (none – fully opinionated)
# ------------------------------------------------------------

# ------------------------------------------------------------
# Dynamic reference to the latest AL2023 Arm64 AMI
# ------------------------------------------------------------
Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64"
  InputFiles:
    Type: CommaDelimitedList
    Default: ''
    Description: 'Comma-separated S3 keys of input files to download'
  ScriptKey:
    Type: String
    Default: ''
    Description: 'S3 key of startup script to run'
  BucketName:
    Type: String
    Description: 'Name of the existing S3 bucket that contains all job inputs and will receive outputs'

# ------------------------------------------------------------
# Instance type parameter (user-configurable)
# ------------------------------------------------------------
  InstanceType:
    Type: String
    Default: r8g.16xlarge
    Description: 'EC2 instance type to launch (must support Nitro Enclaves). Defaults to r8g.16xlarge.'

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  JobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: PutOnlyResults
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:aws:s3:::${BucketName}/jobs/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

  JobInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref JobRole

  JobInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 800
            VolumeType: gp3
            DeleteOnTermination: true
      IamInstanceProfile: !Ref JobInstanceProfile
      EnclaveOptions:
        Enabled: true
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              set -euo pipefail

              # ----------------------------------------------------------
              # Install AWS CLI & tmux
              # ----------------------------------------------------------

              dnf install -y aws-cli tmux || yum install -y aws-cli tmux || true
              
              # ----------------------------------------------------------
              # Write a script (named run_userdata.sh) that will download 
              # the user's files (if any) and script (if any) from the 
              # S3 bucket, and then run the user's script in a tmux session
              # (so the user can attach to the session later and inspect it).
              # ----------------------------------------------------------

              # Directories used by this template
              EC2_USER_HOME="/home/ec2-user"
              SETUP_DIR="$EC2_USER_HOME/setup"
              JOB_DIR="$EC2_USER_HOME/job"

              mkdir -p "$SETUP_DIR" "$JOB_DIR"
              chown -R ec2-user:ec2-user "$EC2_USER_HOME"

              # Write the helper script inside $SETUP_DIR so it is kept
              # separate from the downloaded user artifacts.

              cat << 'EOF_SCRIPT' > "$SETUP_DIR/run_userdata.sh"
              #!/bin/bash
              set -euo pipefail
              echo "Starting UserData in tmux session..."
              DOWNLOAD_DIR="$HOME/job"

              if [ -n "${Files}" ]; then
                for KEY in $(echo "${Files}" | tr ',' ' '); do
                  # Extract just the filename without the path
                  FILENAME=$(basename "$KEY")
                  until aws s3 cp s3://${Bucket}/$KEY "$DOWNLOAD_DIR/$FILENAME"; do
                    echo "Waiting for s3://${Bucket}/$KEY..."
                    sleep 5
                  done
                  echo "Downloaded $KEY to $DOWNLOAD_DIR/$FILENAME"
                done
              fi

              SCRIPT_PATH="${Script}"
              if [ -n "$SCRIPT_PATH" ]; then
                # Extract just the filename without the path
                SCRIPT_FILENAME=$(basename "$SCRIPT_PATH")
                until aws s3 cp s3://${Bucket}/$SCRIPT_PATH "$DOWNLOAD_DIR/$SCRIPT_FILENAME"; do
                  echo "Waiting for s3://${Bucket}/$SCRIPT_PATH..."
                  sleep 5
                done
                chmod +x "$DOWNLOAD_DIR/$SCRIPT_FILENAME"
                bash "$DOWNLOAD_DIR/$SCRIPT_FILENAME"
                echo "Ran script $DOWNLOAD_DIR/$SCRIPT_FILENAME"
              fi
              echo "UserData tasks complete."
              EOF_SCRIPT

              # ----------------------------------------------------------
              # Make the helper script executable
              # ----------------------------------------------------------

              chmod +x "$SETUP_DIR/run_userdata.sh"
              chown ec2-user:ec2-user "$SETUP_DIR/run_userdata.sh"

              # ----------------------------------------------------------
              # Ensure ec2-user has AWS credentials access
              # ----------------------------------------------------------
              
              # Ensure ec2-user can access AWS credentials via instance profile
              mkdir -p "$EC2_USER_HOME/.aws"
              cat << 'EOF_AWS' > "$EC2_USER_HOME/.aws/config"
              [default]
              region = ${AWS::Region}
              EOF_AWS
              chown -R ec2-user:ec2-user "$EC2_USER_HOME/.aws"
              
              # ----------------------------------------------------------
              # Configure tmux defaults for better operator experience
              # ----------------------------------------------------------

              # Create tmux config for ec2-user
              cat << 'EOF_TMUX' > "$EC2_USER_HOME/.tmux.conf"
              # keep more lines in the scrollback buffer
              set -g history-limit 50000
              # let you scroll with your mouse wheel
              set -g mouse on
              EOF_TMUX
              chown ec2-user:ec2-user "$EC2_USER_HOME/.tmux.conf"

              # ----------------------------------------------------------
              # Launch the UserData script in a named, detached tmux 
              # session as ec2-user
              # ----------------------------------------------------------

              # We purposely keep the pane open after the script finishes so
              # that operators can later attach (e.g. via `tmux attach
              # -t userdata`) and inspect all scroll-back.

              # Run tmux as ec2-user
              sudo -u ec2-user tmux new-session -d -s userdata \
              "bash -lc '$SETUP_DIR/run_userdata.sh; EXIT=\$?; echo \"[run_userdata.sh exited with code \$EXIT] UserData complete. You can now inspect the logs.\"; echo \"Type exit or press Ctrl+D to close this pane.\"; exec bash -i'"
            - Bucket: !Ref BucketName
              Files: !Join [ ",", !Ref InputFiles ]
              Script: !Ref ScriptKey

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  BucketName:
    Description: "Bucket that stores job inputs and outputs"
    Value: !Ref BucketName
  InstanceId:
    Description: "EC2 instance ID"
    Value: !Ref JobInstance
